token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhiZThjNDYzMzU0N2NiZmZhMGZiZSIsImlhdCI6MTcxNzMyNjAwMSwiZXhwIjoxNzMyODc4MDAxfQ.EHaFISn__FMPaf1WUeTwUO5qvpgWREpuQj0kGbaefGw'
unit_uri = "https://api.coolremote.net/api/v2/units"
system_uri = "https://api.coolremote.net/api/v2/service-params/systems/"

service_uri = "https://api.coolremote.net/api/v2/service-params"

google_creds = ''
base_aggregation = {
    'System Identifier': 'first',
    'AirNet Addr.': 'first',
    'Centralised Address': 'first',
    'CA Device Line Number': 'first',
    '*Line quality': 'mean',
    'System number': 'first',
    'Indoor Type Code': 'first',
    'System ID': 'first',
    'HVAC Unit type': 'first',
    'Refrigerant System Number': 'first',
    'Generic system number': 'first',
    'Indoor ID': 'first',
    'Indoor ON/OFF Status': 'last',
    'ON/OFF': 'last',
    'Mode': 'last',
    'Filter status': 'last',
    'EV Opening': 'last',
    'Backup ope.': 'last',
    'Cool/Heat parallel ope.': 'last',
    'Cooling': 'last',
    'Comp.1 Disch. stepping down cntl': 'last',
    'Comp.1 INV stepping down cntl': 'last',
    'Comp.2 Disch. stepping down cntl': 'last',
    'Comp.2 INV stepping down cntl': 'last',
    'Compressor 1(INV1)': 'last',
    'Compressor 2(INV2)': 'last',
    'Defrost': 'last',
    'Disch. pipe retry': 'last',
    'Demand state': 'last',
    'Demand stepping down cntl': 'last',
    'EVM (Main)': 'last',
    'EVT (subcooling heat xchanger)': 'last',
    'EVJ (refrigerant injection)': 'last',
    'Fan step': 'last',
    'Heating': 'last',
    'High pressure retry': 'last',
    'HP': 'last',
    'H.P. stepping down cntl': 'last',
    'INV1 Fin stepping down cntl': 'last',
    'INV1 stand-by': 'last',
    'INV2 Fin stepping down cntl': 'last',
    'INV2 stand-by': 'last',
    'Low pressure retry': 'last',
    'L.P. stepping down cntl': 'last',
    'Overheating stand-by': 'last',
    'Oil return': 'last',
    'INV1 oil separator below': 'last',
    'INV2 oil separator below': 'last',
    'Operation control mode': 'last',
    'Operation output': 'last',
    'Restart stand-by': 'last',
    'Startup control': 'last',
    'System HP': 'last',
    'Thermostat ON': 'last',
    'Unit Error stat': 'last',
    'Ventilation': 'last',
    'Target Condensing Pressure': 'last',
    'Target Evaporation Pressure': 'last',
    '*Working hours': 'last',
    '*Comp 1 INV working hours': 'last',
    '*Comp 2 INV working hours': 'last',
    'Target Condensing T': 'last',
    'Target Evaporation T': 'last',
    '*Electric Power (Estimated)': 'mean',
    'Indoor Set Temperature': 'mean',
    'Room Temp': 'mean',
    'Set Temp': 'mean',
    'Site temperature': 'mean',
    'Suction T°': 'mean',
    'Liquid T°': 'mean',
    'Gas Pipe T°': 'mean',
    'Air Thermistor BRC1 T°': 'mean',
    'Outdoor ambient temperature': 'mean',
    'Ambient temperature': 'mean',
    'Condensing Temperature': 'mean',
    'Comp.1 current': 'mean',
    'Comp.2 current': 'mean',
    'Comp. suction pipe temp.': 'mean',
    'Discharge pipe temp.(Comp.1)': 'mean',
    'Discharge pipe temp.(Comp.2)': 'mean',
    'INV1 comp. body temp': 'mean',
    'INV2 comp. body temp': 'mean',
    'Evaporating Temperature': 'mean',
    'Fan 1 rotation amount': 'mean',
    'Fan 2 rotation amount': 'mean',
    'Heat exchanger liquid pipe temp.': 'mean',
    'INV1 fin temp.': 'mean',
    'INV 1 rotation amount': 'mean',
    'INV2 fin temp.': 'mean',
    'INV 2 rotation amount': 'mean',
    'INV FAN current': 'mean',
    'I/U thermostat ON capacity': 'mean',
    'Subcooling heat exchanger gas temp.': 'mean',
    'Subcooling heat exchanger liquid temp.': 'mean',
    'System Current': 'mean',
    'Evaporating Pressure': 'mean',
    'Condensing Pressure': 'mean'
}

cu_agg = {
    'System Identifier': 'first',
    'AirNet Addr.': 'first',
    'Centralised Address': 'first',
    'CA Device Line Number': 'first',
    '*Line quality': 'mean',
    'HVAC Unit type': 'first',
    'Refrigerant System Number': 'first',
    'Generic system number': 'first',
    'Comp.1 Disch. stepping down cntl': 'last',
    'Comp.1 INV stepping down cntl': 'last',
    'Comp.2 Disch. stepping down cntl': 'last',
    'Comp.2 INV stepping down cntl': 'last',
    'Compressor 1(INV1)': 'last',
    'Compressor 2(INV2)': 'last',
    'Defrost': 'last',
    'Disch. pipe retry': 'last',
    'Demand state': 'last',
    'Demand stepping down cntl': 'last',
    'EVM (Main)': 'last',
    'EVT (subcooling heat xchanger)': 'last',
    'EVJ (refrigerant injection)': 'last',
    'Fan step': 'last',
    'Heating': 'last',
    'High pressure retry': 'last',
    'HP': 'last',
    'H.P. stepping down cntl': 'last',
    'INV1 Fin stepping down cntl': 'last',
    'INV1 stand-by': 'last',
    'INV2 Fin stepping down cntl': 'last',
    'INV2 stand-by': 'last',
    'Low pressure retry': 'last',
    'L.P. stepping down cntl': 'last',
    'Overheating stand-by': 'last',
    'Oil return': 'last',
    'INV1 oil separator below': 'last',
    'INV2 oil separator below': 'last',
    'Operation control mode': 'last',
    'Operation output': 'last',
    'Restart stand-by': 'last',
    'Startup control': 'last',
    'System HP': 'last',
    'Thermostat ON': 'last',
    'Unit Error stat': 'last',
    'Ventilation': 'last',
    'Target Condensing Pressure': 'last',
    'Target Evaporation Pressure': 'last',
    '*Comp 1 INV working hours': 'last',
    '*Comp 2 INV working hours': 'last',
    'Target Condensing T': 'last',
    'Target Evaporation T': 'last',
    '*Electric Power (Estimated)': 'mean',
    'Comp.1 current': 'mean',
    'Comp.2 current': 'mean',
    'Comp. suction pipe temp.': 'mean',
    'Discharge pipe temp.(Comp.1)': 'mean',
    'Discharge pipe temp.(Comp.2)': 'mean',
    'INV1 comp. body temp': 'mean',
    'INV2 comp. body temp': 'mean',
    'Evaporating Temperature': 'mean',
    'Fan 1 rotation amount': 'mean',
    'Fan 2 rotation amount': 'mean',
    'Heat exchanger liquid pipe temp.': 'mean',
    'INV1 fin temp.': 'mean',
    'INV 1 rotation amount': 'mean',
    'INV2 fin temp.': 'mean',
    'INV 2 rotation amount': 'mean',
    'INV FAN current': 'mean',
    'I/U thermostat ON capacity': 'mean',
    'Subcooling heat exchanger gas temp.': 'mean',
    'Subcooling heat exchanger liquid temp.': 'mean',
    'System Current': 'mean',
    'Evaporating Pressure': 'mean',
    'Condensing Pressure': 'mean',
    'Site temperature': 'mean'  # from base_aggregation
}

fcu_agg = {
    'System Identifier':'first',
    '*Working hours': 'last',
    'Air Thermistor BRC1 T°': 'mean',
    'EV Opening': 'last',
    'Filter status': 'last',
    'Gas Pipe T°': 'mean',
    'Indoor ID': 'first',
    'Indoor ON/OFF Status': 'last',
    'Indoor Set Temperature': 'mean',
    'Indoor Type Code': 'first',
    'Liquid T°': 'mean',
    'Mode': 'last',
    'ON/OFF': 'last',
    'Room Temp': 'mean',
    'Suction T°': 'mean',
    'Set Temp': 'mean',
    'Site temperature': 'mean',
}

values = ['Time Stamp','Unit Name','Unit Type','AirNet Addr.','Centralised Address','Indoor ON/OFF Status','CA Device Line Number','HVAC Unit type','Refrigerant System Number','Indoor Set Temperature','Generic system number','*Comp 1 INV working hours','*Comp 2 INV working hours','*Line quality','*Working hours','ON/OFF','Room Temp','Set Temp','Mode','Fan Mode','*Failure','Indoor therm ON status','Outdoor ambient temperature','Filter status','Site temperature','*Electric Power (Estimated)','Fan Mode.1','Mode.1','Suction T°','Liquid T°','Gas Pipe T°','EV Opening','Air Thermistor BRC1 T°','System number','Indoor Type Code','Indoor ID','Central Address','System ID','Ambient temperature','Backup ope.','Cool/Heat parallel ope.','Cooling','Condensing Temperature','Comp.1 current','Comp.1 Disch. stepping down cntl','Compressor 1(INV1)','Comp.1 INV stepping down cntl','Comp.2 current','Comp.2 Disch. stepping down cntl','Compressor 2(INV2)','Comp.2 INV stepping down cntl','Comp. suction pipe temp.','Defrost','Disch. pipe retry','Demand state','Demand stepping down cntl','Discharge pipe temp.(Comp.1)','Discharge pipe temp.(Comp.2)','INV1 comp. body temp','INV2 comp. body temp','Error Code','EVM (Main)','EVT (subcooling heat xchanger)','EVJ (refrigerant injection)','Evaporating Temperature','Fan 1 rotation amount','Fan 2 rotation amount','Fan step','Heating','Heat exchanger liquid pipe temp.','High pressure retry','HP','H.P. stepping down cntl','INV1 Fin stepping down cntl','INV1 fin temp.','INV 1 rotation amount','INV1 stand-by','INV2 Fin stepping down cntl','INV2 fin temp.','INV 2 rotation amount','INV2 stand-by','INV FAN current','I/U thermostat ON capacity','Low pressure retry','L.P. stepping down cntl','Overheating stand-by','Oil return','INV1 oil separator below','INV2 oil separator below','Operation control mode','Operation output','Restart stand-by','Subcooling heat exchanger gas temp.','Subcooling heat exchanger liquid temp.','Startup control','System Current','System HP','Target Condensing T','Target Evaporation T','Thermostat ON','Unit Error stat','Ventilation','Target Condensing Pressure','Target Evaporation Pressure','Evaporating Pressure','Condensing Pressure','Comp.1 current.1','Heat exchanger liquid pipe temp..1','Startup control.1','Comp.2 current.1','Subcooling heat exchanger liquid temp..1','Outdoor Type','Defrost.1','Error Code.1','Error Code.2','Error Code.3','Unit Type.1','Defrost.2','Mode.2','Defrost.3','HP.1','Fan Mode.2','Error Code.4','HP.2','Central Address.1','Fan Mode.3','Defrost.4','HP.3','Mode.3','Error Code.5','HP.4','Error Code.6','Mode.4','Defrost.5','Mode.5','Error Code.7','HP.5','Error Code.8','Error Code.9','Mode.6','HP.6','Error Code.10','System HP.1','Defrost.6','Unit Type.2','Fan Mode.4']

# for key in fcu_agg.keys():
#     if key in values:
#         continue
#     else:
#         print(key)
    
